name: "creating ECR using terraform and github actions workflow"
on:
  push:
    branches:
        - main

env:
  # AWS credentials and Terraform state bucket
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-east-2

jobs:
  terraform:
    name: "Apply Terraform code changes"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Format Terraform files
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"


      - name: Create Terraform execution plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Apply Terraform changes
        if: success()
        run: terraform apply -auto-approve


